### ISSUE TITLE
Can´t get it working

### ISSUE THREAD

**Issue by layoutzweb** [GomatoX/sass-compiler#3]
Hi, I been trying you sass compiler for Atom but i can´t get it to compile to the right folder, I must be doing something wrong in the paths, could you provide me with a exemple so it compiles the scss files to the css folder in the following structure:

> project root:
     > assets
          > css
          > sass
     >inde.html

Thank you!

**Comment by layoutzweb** [comment]
I actually found the problem an submited a pull request, it was related to the output path being ignored when "path extraction" was enabled, it´s fixed now, hope you can merge it.

Regards.

**Comment by GomatoX** [comment]
Thanks for response. Pull merged.
